name: Deploy and Test Dev

on:
  pull_request:
    branches: dev
  push:
    branches: dev

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  test-dev:
    uses: ./.github/workflows/firebase-test.yaml
    secrets: inherit
    with:
      environment: dev
      github_ref: ${{ github.ref }}
      firebase_project: ${{ vars.FIREBASE_PROJECT_DEV }}
